---
- name: Source nvm and install node 12.11.0
  shell: mkdir -p ~/.nvm && export NVM_DIR="$HOME/.nvm" && source $(brew --prefix nvm)/nvm.sh && nvm install 12.11.0
  changed_when: false
  args:
    warn: false
- name: Install global NPM packages
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
    executable: "~/.nvm/versions/node/v12.11.0/bin/npm"
  with_items: "{{ npm_packages }}"

- name: Install global Pip packages
  become: true
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "/usr/local/bin/pip"
  with_items: "{{ pip_packages }}"
