---
- name: "ZSH - Check if ZSH is installed"
  stat:
    path: ~/.oh-my-zsh
  register: zsh_exists

- name: "ZSH - Check if ZSH custom plugins are installed"
  stat:
    path: ~/.oh-my-zsh/custom/plugins
  register: zsh_custom_plugins

- name: "ZSH - Installing oh-my-zsh"
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash -
  when: zsh_exists.stat.exists|bool != true

- name: "ZSH - Setting up plugins - zsh-nvm"
  shell: cd ~/.oh-my-zsh/custom/plugins && git clone git://github.com/lukechilds/zsh-nvm.git
  when: zsh_custom_plugins.stat.exists|bool != true

- name: "ZSH - Add brew zsh to /etc/shells"
  become: true
  lineinfile:
    path: /etc/shells
    state: present
    regexp: '^/usr/local/bin/zsh'
    line: '/usr/local/bin/zsh'

- name: "ZSH - Setting default shell"
  become: true
  shell: "chsh -s $(which zsh)"
  when: not zsh_exists.stat.exists
  register: chsh_result
  changed_when: "'chsh: no changes made' not in chsh_result.stderr"

- name: "SpaceVim - Installing space vim"
  shell: curl -sLf https://spacevim.org/install.sh | bash -s -- --install vim
  changed_when: false
  args:
    warn: false

- name: Clone required repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.branch }}"
    key_file: "{{ item.key_file }}"
    force: true
    accept_hostkey: true
    update: false
  with_items: "{{ repositories_for_clone }}"

# - name: "SDK MAN - Install SDK MAN"
#   command: curl -s "https://get.sdkman.io" | bash