---
- name: "General - Set appearance"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleAquaColorVariant', type: int, value: "{{ General_AppleAquaColorVariant }}" }
  when: General_AppleAquaColorVariant is defined

- name: "General - Use Dark menu bar and Dock"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleInterfaceStyle', type: string, value: "{{ General_AppleInterfaceStyle }}" }
  when: General_AppleInterfaceStyle is defined
  notify:
    - restart MenuBar
    - restart Dock

- name: "General - Automatically hide and show the menu bar"
  osx_defaults: { domain: 'NSGlobalDomain', key: '_HIHideMenuBar', type: bool, value: "{{ General_AutoHideMenuBar }}" }
  when: General_AutoHideMenuBar is defined
  notify: restart MenuBar

- name: "General - Highlight color"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleHighlightColor', type: string, value: "{{ item.value }}" }
  with_items:
    - { name: Red, value: "1.000000 0.733333 0.721569" }
    - { name: Orange, value: "1.000000 0.874510 0.701961" }
    - { name: Yellow, value: "1.000000 0.937255 0.690196" }
    - { name: Green, value: "0.752941 0.964706 0.678431" }
    - { name: Blue, value: "0.695422 0.843986 0.997528" }
    - { name: Purple, value: "0.968627 0.831373 1.000000" }
    - { name: Pink, value: "1.000000 0.749020 0.823529" }
    - { name: Brown, value: "0.929412 0.870588 0.792157" }
    - { name: Graphite, value: "0.847059 0.847059 0.862745" }
  when: General_AppleHighlightColor is defined and item.name == General_AppleHighlightColor

- name: "General - Sidebar icon size"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSTableViewDefaultSizeMode', type: int, value: "{{ General_SidebarIconSize }}" }
  when: General_SidebarIconSize is defined

- name: "General - Scroll bar visibility"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleShowScrollBars', type: string, value: "{{ General_AppleShowScrollBars }}" }
  when: General_AppleShowScrollBars is defined

- name: "General - Scroll bar click behavior"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleScrollerPagingBehavior', type: bool, value: "{{ General_AppleScrollerPagingBehavior }}" }
  when: General_AppleScrollerPagingBehavior is defined

- name: "General - Ask to keep changes when closing documents"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSCloseAlwaysConfirmsChanges', type: bool, value: "{{ General_NSCloseAlwaysConfirmsChanges }}" }
  when: General_NSCloseAlwaysConfirmsChanges is defined

- name: "General - Close windows when quitting an application"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSQuitAlwaysKeepsWindows', type: bool, value: "{{ not General_CloseWindowsWhenQuittingApp }}" }
  when: General_CloseWindowsWhenQuittingApp is defined
  
- name: "General - Extra - Smooth scrolling"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSScrollAnimationEnabled', type: bool, value: "{{ General_NSScrollAnimationEnabled }}" }
  when: General_NSScrollAnimationEnabled is defined

- name: "General - Disabling automatic termination of inactive apps"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSDisableAutomaticTermination', type: bool, value: "{{ General_NSDisableAutomaticTermination }}" }
  when: General_NSDisableAutomaticTermination is defined

- name: "General - Expanding the save panel by default - save mode"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSNavPanelExpandedStateForSaveMode', type: bool, value: "{{ General_NSNavPanelExpandedStateForSaveMode }}" }
  when: General_NSNavPanelExpandedStateForSaveMode is defined

- name: "General - Expanding the save panel by default - print"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'PMPrintingExpandedStateForPrint', type: bool, value: "{{ General_PMPrintingExpandedStateForPrint }}" }
  when: General_PMPrintingExpandedStateForPrint is defined

- name: "General - Expanding the save panel by default - print2"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'PMPrintingExpandedStateForPrint2', type: bool, value: "{{ General_PMPrintingExpandedStateForPrint2 }}" }
  when: General_PMPrintingExpandedStateForPrint2 is defined

- name: "General - Automatically quit printer app once the print jobs complete"
  command: defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
  when: General_PrintingPrefsQuitWhenFinished is defined
  changed_when: false

- name: "General - Setting trackpad & mouse speed to a reasonable number"
  shell: defaults write -g com.apple.trackpad.scaling "{{ General_TrackPadScaling }}" && defaults write -g com.apple.mouse.scaling "{{ General_MouseScaling }}"
  when: General_MouseTrackPadScaling is defined and General_TrackPadScaling is defined and General_MouseScaling is defined
  changed_when: false

- name: "General - Preventing Time Machine from prompting to use new hard drives as backup volume"
  shell: defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
  when: General_DoNotOfferNewDisksForBackup is defined
  changed_when: false

- name: "General - Setting screenshots location and filetype"
  shell: defaults write com.apple.screencapture location -string "{{ General_ScreenshotLocation }}" && defaults write com.apple.screencapture type -string "{{ General_ScreenshotFileType }}"
  when: General_ScreenshotLocation is defined and General_ScreenshotFileType is defined
  changed_when: false

- name: "General - Use specific folder to store incomplete downloads"
  shell: defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true && defaults write org.m0k.transmission IncompleteDownloadFolder -string "{{ General_IncompleteDownloadFolderPath }}"
  when: General_UseIncompleteDownloadFolder is defined and General_IncompleteDownloadFolderPath is defined
